### ISSUE TITLE
Error on import of robjects. No module named '_rinterface_cffi_abi'

### ISSUE THREAD

**Issue by danielward27** [rpy2/rpy2#1175]
The following occurs for me, but only with python=3.13 (not 3.12), when importing robjects: 
```
Traceback:
.pixi/envs/dev/lib/python3.13/site-packages/rpy2/rinterface_lib/openrlib.py:17: in <module>
    import _rinterface_cffi_api as _rinterface_cffi  # type: ignore
E   ModuleNotFoundError: No module named '_rinterface_cffi_api'

During handling of the above exception, another exception occurred:
.pixi/envs/dev/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_gam.py:1: in <module>
    import rpy2.robjects as ro
.pixi/envs/dev/lib/python3.13/site-packages/rpy2/robjects/__init__.py:16: in <module>
    import rpy2.rinterface as rinterface
.pixi/envs/dev/lib/python3.13/site-packages/rpy2/rinterface.py:21: in <module>
    from rpy2.rinterface_lib import openrlib
.pixi/envs/dev/lib/python3.13/site-packages/rpy2/rinterface_lib/openrlib.py:24: in <module>
    raise ie_abi
.pixi/envs/dev/lib/python3.13/site-packages/rpy2/rinterface_lib/openrlib.py:20: in <module>
    import _rinterface_cffi_abi as _rinterface_cffi  # type: ignore
E   ModuleNotFoundError: No module named '_rinterface_cffi_abi'

```
I'm using rpy2=3.5.17, and installing on ubuntu using pixi (adding rpy2 as a pypi dependency).  My pyproject.toml is:
```toml
[project]
name = "pymgcv"
#  requires-python = ">= 3.11, <= 3.12"  # Works
requires-python = ">=3.13"

version = "0.0.0"

dependencies = ["rpy2"]

[project.optional-dependencies]
dev = ["pytest"]

[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]


[tool.pytest.ini_options]
pythonpath = ["."]

# ------------------- pixi config --------------------#

[tool.pixi.dependencies]
r-base = "*"
cffi = ">=1.17.1,<2"        # https://github.com/rpy2/rpy2/issues/739
setuptools = ">=80.1.0,<81"


[tool.pixi.pypi-dependencies]
pymgcv = { path = ".", editable = true }

[tool.pixi.pypi-options]
no-build-isolation = ["rpy2"]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["linux-64"]


[tool.pixi.environments]
dev = ["dev"]
```
I am using r-base-4.4.3.
